apiVersion: v1
kind: Pod
metadata:
  namespace: default
  name: my-app
  labels:
    app: my-app
spec:
  terminationGracePeriodSeconds: 0
  containers:
    - name: my-app
      image: quay.io/kubermatic-labs/training-application:2.0.0
      ports:
        - containerPort: 8080
      imagePullPolicy: Always
      env:
        - name: MY_NODE_NAME
          valueFrom:
            fieldRef:
              fieldPath: spec.nodeName
        - name: MY_POD_NAME
          valueFrom:
            fieldRef:
              fieldPath: metadata.name
        - name: MY_POD_IP
          valueFrom:
            fieldRef:
              fieldPath: status.podIP
      volumeMounts:
        - name: podinfo
          mountPath: /etc/podinfo
  volumes:
    - name: podinfo
      downwardAPI:
        items:
          - path: "labels"
            fieldRef:
              fieldPath: metadata.labels
          - path: "annotations"
            fieldRef:
              fieldPath: metadata.annotations
