apiVersion: v1
kind: Pod
metadata:
    namespace: default
    name: my-app
    labels:
        app: my-app
spec:
    terminationGracePeriodSeconds: 0
    containers:
        - name: my-app
          image: eu.gcr.io/kubermatic-training-playground/kubermatic-training/app:0.0.1
          ports:
            - containerPort: 8080
          imagePullPolicy: Always
