apiVersion: v1
kind: Pod
metadata:
  name: pod-b
  labels:
    app: pod-b
spec:
  containers:
    - name: kad-go-application
      image: quay.io/kubermatic-labs/kad-training:1.0.0-go
      imagePullPolicy: Always
      ports:
        - name: http
          containerPort: 8080