apiVersion: v1
kind: Pod
metadata:
  name: {{ .Chart.Name }}
spec:
  terminationGracePeriodSeconds: 0
  containers:
    - name: curl
      image: nicolaka/netshoot
      command:
        - "/bin/sh"
        - "-c"
        - "sleep infinity;"
        