apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-deployment
spec:
  template:
    spec:
      containers:
      - name: my-nginx
        resources:
          limits:
            memory: 200Mi
          requests:
            memory: 200Mi
