apiVersion: batch/v1
kind: Job
metadata:
  namespace: my-namespace
  name: my-curl
spec:
  template:
    spec:
      containers:
        - name: my-curl
          image: eu.gcr.io/loodse-training-playground/loodse-training/curl:0.0.1
          args: [ "my-app" ]
          imagePullPolicy: Always
      restartPolicy: Never

