FROM golang:1.21.4-bookworm as builder
WORKDIR /src
COPY go.mod go.sum ./
RUN go mod download
COPY main.go ./
RUN go build -o training-application

FROM gcr.io/distroless/static-debian12
WORKDIR /app
COPY --from=builder /src/training-application /app/training-application
COPY conf/app.conf ./conf/
ENTRYPOINT [ "./training-application" ]