FROM golang:alpine3.15 as builder
WORKDIR /src
COPY go.mod go.sum ./
RUN go mod download
COPY *.go ./
RUN CGO_ENABLED=0 go build -o training-application

FROM gcr.io/distroless/static-debian12
COPY --from=builder /src/training-application /
COPY conf/app.conf /conf/
ENTRYPOINT [ "/training-application" ]
