FROM --platform=linux/amd64 golang:1.21.4-bookworm as builder
WORKDIR /src
COPY go.mod go.sum ./
RUN go mod download
COPY main.go ./
RUN go build -o kad-training

FROM --platform=linux/amd64 ubuntu:22.04
WORKDIR /app
COPY --from=builder /src/kad-training /app/kad-training
COPY app.conf ./
ENTRYPOINT ./kad-training
