apiVersion: v1
kind: Pod
metadata:
  namespace: default
  name: my-app
  labels:
    app: my-app
spec:
  terminationGracePeriodSeconds: 30
  containers:
    - name: my-app
      image: eu.gcr.io/loodse-training-playground/loodse-training/app:0.0.1
      ports:
        - containerPort: 8080
      imagePullPolicy: Always
      livenessProbe:
        initialDelaySeconds: 10
        httpGet:
          port: 8080
          path: /actuator/liveness
      readinessProbe:
        initialDelaySeconds: 0
        httpGet:
          port: 8080
          path: /actuator/readiness                
      volumeMounts:
        - name: my-volume
          mountPath: /srv/app/config
  volumes:
    - name: my-volume
      configMap:
        name: my-configmap
