apiVersion: v1
kind: Pod
metadata:
  name: my-pod
spec:
  containers:
    - name: my-ubuntu
      image: ubuntu
      args: ["sleep", "1d"]
      securityContext:
        readOnlyRootFilesystem: true
