apiVersion: v1
kind: Pod
metadata:
  namespace: default
  name: my-app
  labels:
    app: my-app
  annotations:
    vault.hashicorp.com/agent-inject: "true"
    vault.hashicorp.com/agent-inject-secret-db-creds: "myapp/secret-data"
    vault.hashicorp.com/agent-inject-template-db-creds: |
      {{- with secret "myapp/secret-data" -}}
      postgres://{{ .Data.data.username }}:{{ .Data.data.password }}@postgres:5432/appdb?sslmode=disable
      {{- end }}
    vault.hashicorp.com/role: "vault-read"
spec:
  containers:
    - name: my-app
      image: quay.io/kubermatic-labs/training-application:2.0.0
      ports:
        - containerPort: 8080
      imagePullPolicy: Always
      volumeMounts:
        - name: my-volume
          mountPath: /srv/app/config
  volumes:
    - name: my-volume
      configMap:
        name: my-configmap
