apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: kubermatic-fast
  annotations:
    storageclass.kubernetes.io/is-default-class: "true"
provisioner: kubernetes.io/gce-pd
reclaimPolicy: Delete
volumeBindingMode: WaitForFirstConsumer
parameters:
  type: pd-ssd
