apiVersion: v1
kind: Pod
metadata:
  name: kad-go-application
spec:
  terminationGracePeriodSeconds: 5
  containers:
    - name: kad-go-application
      image: quay.io/kubermatic-labs/training-application:2.0.0
      imagePullPolicy: Always
