apiVersion: v1
kind: Pod
metadata:
  name: app
spec:
  terminationGracePeriodSeconds: 5
  containers:
    - name: app
      image: quay.io/kubermatic-labs/training-application:2.0.0
      imagePullPolicy: Always
