apiVersion: v1
kind: Pod
metadata:
  name: kad-go-application-a
  labels:
    app: app-a
spec:
  terminationGracePeriodSeconds: 12
  containers:
    - name: kad-go-application-a
      image: quay.io/kubermatic-labs/kad-training:1.0.1-go
      imagePullPolicy: Always
  affinity:
    podAffinity:
      preferredDuringSchedulingIgnoredDuringExecution:
      - weight: 100
        podAffinityTerm:
          labelSelector:
            matchExpressions:
            - key: app
              operator: In
              values:
              - app-b
          topologyKey: kubernetes.io/hostname