apiVersion: v1
kind: Pod
metadata:
  name: kad-go-application
spec:
  terminationGracePeriodSeconds: 5
  containers:
    - name: kad-go-application
      image: quay.io/kubermatic-labs/kad-training:1.0.0-go
      imagePullPolicy: Always
