apiVersion: v1
kind: ConfigMap
metadata:
  namespace: default
  name: my-configmap
data: 
  application.properties: |-
    management.endpoints.web.exposure.include=prometheus,liveness,readiness
    server.port=8081
