apiVersion: v1
kind: Pod
metadata:
  namespace: default
  name: my-app
  labels:
    app: my-app
spec:
  terminationGracePeriodSeconds: 0
  containers:
    - name: my-app
      image: eu.gcr.io/loodse-training-playground/loodse-training/app:0.0.1
      ports:
        - containerPort: 8080
      imagePullPolicy: Always
      volumeMounts:
        - name: my-volume
          mountPath: /srv/app/config
  volumes:
    - name: my-volume
      configMap:
        name: my-configmap
