apiVersion: v1
kind: Pod
metadata:
  name: my-addon-pod
  namespace: default
spec:
  containers:
    - name: my-addon-container
      image: alpine:3.16.0
      command: [ "/bin/sh", "-c", "--" ]
      args: [ "while true; do echo $(date); sleep 1; done;" ]
      resources:
        requests:
          cpu: "100m"
          memory: "64Mi"
        limits:
          cpu: "100m"
          memory: "64Mi"
