apiVersion: certificates.k8s.io/v1
kind: CertificateSigningRequest
metadata:
  name: bob
spec:
  signerName: kubernetes.io/kube-apiserver-client
  request: $CSR
  usages:
    - digital signature
    - key encipherment
    - client auth
