FROM --platform=linux/amd64 golang:1.21.4-bookworm as builder
WORKDIR /src
COPY go.mod go.sum ./
RUN go mod download
COPY *.go ./
RUN go build -o seven-sins

FROM --platform=linux/amd64 ubuntu:22.04
WORKDIR /app
COPY --from=builder /src/seven-sins /app/seven-sins
ENTRYPOINT [ "./seven-sins" ]
