apiVersion: v1
kind: Pod
metadata:
  name: app-a
  labels:
    app: app-a
spec:
  terminationGracePeriodSeconds: 12
  containers:
    - name: app-a
      image: quay.io/kubermatic-labs/training-application:2.0.0-A
      imagePullPolicy: Always
  affinity:
    podAffinity:
      preferredDuringSchedulingIgnoredDuringExecution:
        - weight: 100
          podAffinityTerm:
            labelSelector:
              matchExpressions:
                - key: app
                  operator: In
                  values:
                    - app-b
            topologyKey: kubernetes.io/hostname
