apiVersion: v1
kind: Pod
metadata:
  name: app-b
  labels:
    app: app-b
spec:
  terminationGracePeriodSeconds: 12
  containers:
    - name: app-b
      image: quay.io/kubermatic-labs/training-application:2.0.0-B
      imagePullPolicy: Always
  affinity:
    podAffinity:
      preferredDuringSchedulingIgnoredDuringExecution:
        - weight: 100
          podAffinityTerm:
            labelSelector:
              matchExpressions:
                - key: app
                  operator: In
                  values:
                    - app-a
            topologyKey: kubernetes.io/hostname
