apiVersion: v1
kind: Pod
metadata:
  name: my-app
spec:
  terminationGracePeriodSeconds: 12
  containers:
    - name: my-app
      image: quay.io/kubermatic-labs/kad-training:1.0.0-go
      imagePullPolicy: Always
      tty: true
      stdin: true
      resources:
        limits:
          cpu: 30m
          memory: 10Mi
        requests:
          cpu: 30m
          memory: 10Mi
