#!/bin/bash

TRAINING_RC_FILE_NODES=~/.node_trainingrc

set -euxo pipefail

rm -rf $TRAINING_RC_FILE_NODES

grep -qxF "export ETCD_VERSION=$ETCD_VERSION" $TRAINING_RC_FILE_NODES || echo "export ETCD_VERSION=$ETCD_VERSION" >> $TRAINING_RC_FILE_NODES
grep -qxF "export KUBERNETES_VERSION=$KUBERNETES_VERSION" $TRAINING_RC_FILE_NODES || echo "export KUBERNETES_VERSION=$KUBERNETES_VERSION" >> $TRAINING_RC_FILE_NODES
