FROM --platform=linux/amd64 golang:alpine3.15 as builder
WORKDIR /src
COPY go.mod go.sum ./
RUN go mod download
COPY *.go ./
RUN go build -o seven-sins

FROM --platform=linux/amd64 gcr.io/distroless/static-debian12
WORKDIR /app
COPY --from=builder /src/seven-sins /app/seven-sins
ENTRYPOINT [ "./seven-sins" ]
