apiVersion: batch/v1
kind: Job
metadata:
  name: {{ .Values.name }}-pre-delete
  annotations:
    "helm.sh/hook": "pre-delete"
spec:
  backoffLimit: 0
  template:
    spec:
      restartPolicy: Never
      containers:
        - name: pre-delete-hook
          image: ubuntu:20.04
          command:
            - echo
          args: 
            - pre-delete-hook
