apiVersion: batch/v1
kind: Job
metadata:
  name: {{ .Values.name }}-pre-install
  annotations:
    "helm.sh/hook": "pre-install"
spec:
  backoffLimit: 0
  template:
    spec:
      restartPolicy: Never
      containers:
        - name: pre-install-hook
          image: ubuntu:20.04
          command:
            - echo
          args: 
            - pre-install-hook
