.PHONY setup:
setup:
	$(MAKE) -C ../kubernetes_fundamentals/ setup

.PHONY verify:
verify:
	$(MAKE) -C ../kubernetes_fundamentals/ verify

.PHONY teardown:
teardown:
	$(MAKE) -C ../kubernetes_fundamentals/ teardown
